"""
Build data/prominent_candidates_26.csv from official party candidate lists.

Sources:
  INC  — INC_candidates.pdf (AICC press release, 3 Apr 2026)
  BJP  — BJP_candidates.pdf (BJP press release, 3 Apr 2026)
  DMK  — The Hindu, full list
  AIADMK — Official list
  TVK  — The Hindu, full list
  CPI(M) — The Hindu, 5 constituencies
  CPI(ML) — cpiml.org

Run:
    python scripts/build_prominent_candidates.py
"""

import csv
import re
from pathlib import Path

OUT = Path("data/prominent_candidates_26.csv")

# ---------------------------------------------------------------------------
# Raw data — (constituency, candidate_name) tuples per party
# ---------------------------------------------------------------------------

INC = [
    ("Ponneri", "Durai Chandrasekar"),
    ("Velachery", "JMH Aassan Maulaana"),
    ("Sriperumbudur", "K. Selvaperunthagai"),
    ("Sholingur", "A.M. Munirathinam"),
    ("Uthangarai", "R. Kuppu Saamy"),
    ("Krishnagiri", "Dr. A. Chella Kumar"),
    ("Pennagaram", "GKM Tamil Kumaran"),
    ("Attur", "S K Arthanari"),
    ("Erode (East)", "Gopinath Palaniyappan"),
    ("Udhagamandalam", "B. Ramachandran"),
    ("Kavundampalayam", "K.P. Surya Prakash"),
    ("Singanallur", "V. Shrinithi Naidu"),
    ("Thuraiyur", "M. Vichu Lenin Prasath"),
    ("Cuddalore", "A.S. Chandrasekaran"),
    ("Mayiladuthurai", "Jamal Yunus Mohammed"),
    ("Aranthangi", "T. Rama Chandhiran"),
    ("Karaikudi", "S. Mangudi"),
    ("Usilampatti", "T. Saravana Kumar"),
    ("Sivakasi", "Ganesan Ashokan"),
    ("Tiruvadanai", "Rama Karumanickam"),
    ("Srivaikuntam", "S. Oorvashi Amirtharaj"),
    ("Sankarankovil", "Sangai Ganeshan"),
    ("Ambasamudram", "V.P. Durai"),
    ("Nanguneri", "Ruby Manoharan"),
    ("Colachel", "Dr. Tharagai Cuthbert"),
    ("Vilavancode", "T.T. Praveen"),
    ("Killiyoor", "S. Rajesh Kumar"),
]

BJP = [
    ("Avadi", "M. Rajasimha Mahindra"),
    ("Mylapore", "Tamilisai Soundararajan"),
    ("Thalli", "Nagesh Kumar"),
    ("Tiruvannamalai", "C. Elumalai"),
    ("Rasipuram", "S.D. Premkumar"),
    ("Modakkurichi", "Kirthika Shivkumar"),
    ("Udhagamandalam", "Bhojarajan"),
    ("Avanashi", "L. Murugan"),
    ("Tiruppur (South)", "S. Thangaraj"),
    ("Coimbatore (North)", "Vanathi Srinivasan"),
    ("Thiruvarur", "Govi Chandru"),
    ("Thanjavur", "M. Muruganandam"),
    ("Gandharvakottai", "C. Udhayakumar"),
    ("Pudukkottai", "N. Ramachandran"),
    ("Aranthangi", "Kavitha Srikanth"),
    ("Tiruppattur", "K.C. Thirumaran"),
    ("Manamadurai", "Pon. V. Balaganapathy"),
    ("Madurai South", "Raama Sreenivasan"),
    ("Sattur", "Nainar Nagenthran"),
    ("Ramanathapuram", "GBS K. Nagendran"),
    ("Tiruchendur", "KRM Radhakrishnan"),
    ("Vasudevanallur", "Ananthan Ayyasamy"),
    ("Radhapuram", "S.P. Balakrishnan"),
    ("Nagercoil", "M.R. Gandhi"),
    ("Colachel", "T. Sivakumar"),
    ("Padmanabhapuram", "P. Ramesh"),
    ("Vilavancode", "S. Vijayadharani"),
]

DMK = [
    ("Alandur", "T.M. Anbarasan"),
    ("Alangudi", "Siva V. Meyyanathan"),
    ("Alangulam", "Paul Manoj Pandian"),
    ("Ambattur", "Dr. A.P. Poornima"),
    ("Ambur", "A.C. Vilvanathan"),
    ("Anaikattu", "A.P. Nandakumar"),
    ("Andipatti", "A. Maharajan"),
    ("Anna Nagar", "N. Chitrarasu"),
    ("Anthiyur", "M. Sivabalan"),
    ("Arani", "Mahalakshmi Govarthanan"),
    ("Aravakurichi", "Monjanour R. Elango"),
    ("Arcot", "J.L. Eswarappan"),
    ("Ariyalur", "Latha Balu"),
    ("Aruppukkottai", "K.K.S.S.R. Ramachandran"),
    ("Athoor", "I. Periyasamy"),
    ("Avadi", "S.M. Nasar"),
    ("Avanashi", "V. Kokila Mani"),
    ("Bargur", "D. Mathiyazhagan"),
    ("Bhavani", "K.A. Chandrasekar"),
    ("Bhuvanagiri", "Durai K. Saravanan"),
    ("Bodinayakkanur", "O. Panneerselvam"),
    ("Chengalpattu", "M.K.D. Karthik Dhandapani"),
    ("Chengam", "M.P. Giri"),
    ("Chepauk-Thiruvallikeni", "Udhayanidhi Stalin"),
    ("Cheyyar", "O. Jothi"),
    ("Coimbatore North", "D. Senthamizh Selvan"),
    ("Coimbatore South", "V. Senthilbalaji"),
    ("Coonoor", "K.M. Raju"),
    ("Cumbum", "N. Ramakrishnan"),
    ("Dharapuram", "T. Indirani"),
    ("Dindigul", "I.P. Senthilkumar"),
    ("Dr. Radhakrishnan Nagar", "J. John Ebenezer"),
    ("Edappadi", "C. Kasi"),
    ("Egmore", "S. Prasanna"),
    ("Erode West", "S. Muthusamy"),
    ("Gangavalli", "K. Chinnadurai"),
    ("Gingee", "Gingee K.S. Masthan"),
    ("Gobichettipalayam", "N. Nallasivam"),
    ("Gudalur", "M. Thiravidamani"),
    ("Gummidipoondi", "T.J. Govindarajan"),
    ("Harbour", "P.K. Sekarbabu"),
    ("Harur", "A. Shanmugam"),
    ("Jayankondam", "K.S.K. Kannan"),
    ("Jolarpet", "Kavitha Dhandapani"),
    ("Kalasapakkam", "P.S.T. Saravanan"),
    ("Kancheepuram", "S. Nithya"),
    ("Kangayam", "M.P. Saminathan"),
    ("Kanniyakumari", "R. Mahesh"),
    ("Karur", "Aasi M. Thiagarajan"),
    ("Katpadi", "Duraimurugan"),
    ("Kilpennathur", "K. Pichandi"),
    ("Kilvaithinankuppam", "Dr. Rajeswari Mohangandhi"),
    ("Kinathukadavu", "S. Sabari Karthikeyan"),
    ("Kolathur", "M.K. Stalin"),
    ("Kovilpatti", "K. Karunanidhi"),
    ("Krishnarayapuram", "C.K. Raja"),
    ("Kulithalai", "Suriyanur A. Chandran"),
    ("Kumarapalayam", "S. Balu"),
    ("Kumbakonam", "G. Anbalagan"),
    ("Kunnam", "S.S. Sivasankar"),
    ("Kurinjipadi", "M.R.K. Panneerselvam"),
    ("Lalgudi", "T. Parivallal Thangavel"),
    ("Madathukulam", "R. Jayaramakrishnan"),
    ("Madhavaram", "S. Sudharsanam"),
    ("Madurai Central", "Palanivel Thiaga Rajan"),
    ("Madurai East", "P. Moorthy"),
    ("Madurai North", "G. Thalapathi"),
    ("Madurai West", "R. Balaji"),
    ("Madurantakam", "S. Ponmalar"),
    ("Maduravoyal", "Karambakkam K. Ganapathy"),
    ("Manamadurai", "A. Tamilarasi"),
    ("Mannachanallur", "S. Kathiravan"),
    ("Mannargudi", "T.R.B. Rajaa"),
    ("Mettupalayam", "K. Kavitha Sundaram"),
    ("Mettur", "M. Midhun Chakaravarthy"),
    ("Mudukulathur", "R.S. Rajakannappan"),
    ("Musiri", "N.S. Karunairaaja"),
    ("Mylapore", "Dha. Velu"),
    ("Nagercoil", "S. Austin"),
    ("Namakkal", "P. Rani"),
    ("Neyveli", "Saba. Rajendran"),
    ("Nilakottai", "S. Nagajothi"),
    ("Orathanadu", "R. Vaithilingam"),
    ("Ottanchatram", "R. Sakkarapani"),
    ("Ottapidaram", "P.M. Ramajeyam"),
    ("Palacode", "Dr. D.N.V. Senthilkumar"),
    ("Palayamkottai", "M. Abdul Wahab"),
    ("Palladam", "K. Selvraj"),
    ("Pappireddippatti", "P. Palaniappan"),
    ("Paramakudi", "K.K. Kathiravan"),
    ("Paramathi Velur", "K.S. Moorthy"),
    ("Pattukkottai", "K. Annadurai"),
    ("Hosur", "S.A. Sathya"),
    ("Perambalur", "S.T. Jayalakshmi"),
    ("Perambur", "R.D. Shekar"),
    ("Peravurani", "N. Asokkumar"),
    ("Perundurai", "Thoppu N.D. Venkatachalam"),
    ("Poompuhar", "Nivedha M. Murugan"),
    ("Poonamallee", "A. Krishnaswamy"),
    ("Pudukkottai", "V. Muthuraja"),
    ("Radhapuram", "M. Appavu"),
    ("Rajapalayam", "S. Thangapandian"),
    ("Ramanathapuram", "Katharbatsha Muthuramalingam"),
    ("Ranipet", "Vinoth Gandhi"),
    ("Rasipuram", "M. Mathiventhan"),
    ("Rishivandiyam", "K. Karthikeyan"),
    ("Royapuram", "Dr. A. Subairkhan"),
    ("Saidapet", "Ma. Subramanian"),
    ("Salem North", "R. Rajendran"),
    ("Salem South", "M. Loganathan"),
    ("Sankarapuram", "T. Udhayasuriyan"),
    ("Sankari", "M. Manikandan"),
    ("Sattur", "A. Kadarkarai Raj"),
    ("Senthamangalam", "P. Poomalar"),
    ("Sholavandan", "A. Venkatesan"),
    ("Sholinganallur", "S. Aravind Ramesh"),
    ("Srirangam", "S. Durairaj"),
    ("Sulur", "Thalapathi Murugeshan"),
    ("T. Nagar", "Raja Anbalagan"),
    ("Tambaram", "Dr. R.S. Kiruthika Devi"),
    ("Tenkasi", "Kalai Kathiravan"),
    ("Thanjavur", "Shan. Ramanathan"),
    ("Thiru-Vi-Ka-Nagar", "K.S. Ravichandran"),
    ("Thiruchuli", "Thangam Thennarasu"),
    ("Thirumayam", "S. Regupathy"),
    ("Thirupparankundram", "Kiruthiga Thangapandi"),
    ("Thiruvaiyaru", "Durai. Chandrasekaran"),
    ("Thiruvarur", "Poondi K. Kalaivanan"),
    ("Thiruvidaimarudur", "Govi. Chezhiaan"),
    ("Thondamuthur", "N.R. Karthikeyan"),
    ("Thoothukudi", "P. Geetha Jeevan"),
    ("Thousand Lights", "Dr. Ezhilan Naganathan"),
    ("Tiruchendur", "Anitha R. Radhakrishnan"),
    ("Tirukkoyilur", "Pon. Gowtham Sigamani"),
    ("Tirumangalam", "Sedapatti M. Manimaran"),
    ("Tirunelveli", "S. Subramanian"),
    ("Tirupattur", "A. Nallathambi"),
    ("Tirupattur", "K.R. Periakaruppan"),
    ("Tiruppur South", "N. Dinesh Kumar"),
    ("Tiruvallur", "V.G. Rajendran"),
    ("Tiruvannamalai", "E.V. Velu"),
    ("Thiruverumbur", "Anbil Mahesh Poyyamozhi"),
    ("Tittakudi", "C.V. Ganesan"),
    ("Tiruchi East", "Dr. S. Inigo Irudayaraj"),
    ("Tiruchi West", "K.N. Nehru"),
    ("Udumalaipettai", "M. Jayakumar"),
    ("Ulundurpettai", "G.R. Vasanthavel"),
    ("Uthiramerur", "K. Sundar"),
    ("Valparai", "A. Sudhakar"),
    ("Vandavasi", "S. Ambeth Kumar"),
    ("Vanur", "D. Gowtham"),
    ("Vasudevanallur", "E. Raja"),
    ("Vedaranyam", "M. Pugazhenthi"),
    ("Vedasandur", "D. Swaminathan"),
    ("Veerapandi", "Dr. A.K. Tarun"),
    ("Vellore", "P. Karthikeyan"),
    ("Veppanahalli", "P.S. Srinivasan"),
    ("Vikravandi", "Anniyur Siva"),
    ("Vilathikulam", "G.V. Markandayan"),
    ("Villivakkam", "Karthik Mohan"),
    ("Villupuram", "R. Lakshmanan"),
    ("Viralimalai", "K.K. Chella Pandiyan"),
    ("Virugambakkam", "A.M.V. Prabhakara Raja"),
    ("Yercaud", "T.M. Revathi Matheswaran"),
]

AIADMK = [
    ("Edappadi", "Edappadi K. Palaniswami"),
    ("Veppanahalli", "K.P. Munusamy"),
    ("Dindigul", "Dindigul C. Sreenivasan"),
    ("Natham", "Natham R. Viswanathan"),
    ("Thondamuthur", "S.P. Velumani"),
    ("Kumarapalayam", "P. Thangamani"),
    ("Royapuram", "D. Jayakumar"),
    ("Mailam", "C.Ve. Shanmugam"),
    ("Madurai West", "Sellur K. Raju"),
    ("Palacode", "K.P. Anbalagan"),
    ("Nannilam", "R. Kamaraj"),
    ("Vedaranyam", "O.S. Manian"),
    ("Viralimalai", "Dr. C. Vijayabaskar"),
    ("Kovilpatti", "Kadambur C. Raju"),
    ("Tirumangalam", "R.B. Udhayakumar"),
    ("Sivakasi", "K.T. Rajenthra Bhalaji"),
    ("Maduravoyal", "P. Benjamin"),
    ("Kalasapakkam", "Agri S.S. Krishnamurthy"),
    ("Thirupparankundram", "V.V. Rajan Chellappa"),
    ("Bhavani", "K.C. Karuppannan"),
    ("Jolarpet", "K.C. Veeramani"),
    ("Karur", "M.R. Vijayabhaskar"),
    ("Ariyalur", "Thamarai S. Rajendran"),
    ("Gummidipoondi", "V. Sudhakar"),
    ("Ponneri", "Siruniam P. Balaraman"),
    ("Tiruttani", "Tiruttani K. Hari"),
    ("Thiruvallur", "B.V. Ramana"),
    ("Madhavaram", "Madhavaram V. Moorthy"),
    ("Thiruvottiyur", "K. Kuppan"),
    ("Sriperumbudur", "K. Palani"),
    ("Tambaram", "Chitlapakkam C. Rajendran"),
    ("Chengalpattu", "M. Gaja Gajendran"),
    ("Cheyyur", "E. Rajasekar"),
    ("Madurantakam", "Maragatham Kumaravel"),
    ("Kancheepuram", "V. Somasundaram"),
    ("Arakkonam", "S. Ravi"),
    ("Katpadi", "V. Ramu"),
    ("Arcot", "S.M. Sukumar"),
    ("Vellore", "S.R.K. Appu"),
    ("Anaicut", "T. Velazhagan"),
    ("Gudiyatham", "G. Paritha Purushothaman"),
    ("Vaniyambadi", "G. Senthilkumar"),
    ("Ambur", "R. Venkatesan"),
    ("Uthangarai", "T.M. Tamilselvam"),
    ("Bargur", "E.C. Govindarajan"),
    ("Krishnagiri", "K. Ashokkumar"),
    ("Hosur", "P. Balakrishna Reddy"),
    ("Pappireddipatti", "Maragatham Vetrivel"),
    ("Aroor", "V. Sampathkumar"),
    ("Chengam", "T.S. Velu"),
    ("Kilpennathur", "S. Ramachandran"),
    ("Arani", "L. Jayasudha"),
    ("Cheyyar", "Mukkur N. Subramanian"),
    ("Vandavasi", "P. Rani"),
    ("Tindivanam", "P. Arjunan"),
    ("Vanur", "P. Murugan"),
    ("Villupuram", "K. Vijaya"),
    ("Tirukoilur", "S. Palanisamy"),
    ("Ulundurpettai", "R. Kumaraguru"),
    ("Sankarapuram", "R. Rakesh"),
    ("Kallakurichi", "S. Rajiv Gandhi"),
    ("Gangavalli", "A. Nallathambi"),
    ("Attur", "A.P. Jayasankaran"),
    ("Yercaud", "P. Usharani"),
    ("Omalur", "R. Mani"),
    ("Mettur", "G. Venkatachalam"),
    ("Sankagiri", "S. Vetrivel"),
    ("Salem South", "J. Vinoth"),
    ("Veerapandi", "Sri Balaji Sukumar"),
    ("Senthamangalam", "C. Chandrasekaran"),
    ("Namakkal", "Sridevi P.S. Mohan"),
    ("Paramathi Velur", "S. Sekar"),
    ("Tiruchengode", "R. Chandrasekar"),
    ("Erode East", "R. Manoharan"),
    ("Dharapuram", "P. Sathyabama"),
    ("Kangayam", "N.S.N. Nataraj"),
    ("Perundurai", "J.K. Jayakumar"),
    ("Anthiyur", "P. Haribhaskar"),
    ("Gobichettipalayam", "V.B. Prabhu"),
    ("Bhavanisagar", "A. Pannari"),
    ("Gudalur", "Pon Jayaseelan"),
    ("Coonoor", "A. Ramu"),
    ("Mettupalayam", "O.K. Chinnaraj"),
    ("Tiruppur North", "M.S.M. Anandan"),
    ("Palladam", "Palladam K.P. Paramasivam"),
    ("Sulur", "V.P. Kandasamy"),
    ("Goundampalayam", "P.R.G. Arunkumar"),
    ("Coimbatore South", "Amman K. Arjunan"),
    ("Singanallur", "K.R. Jayaram"),
    ("Kinathukadavu", "S. Damodaran"),
    ("Pollachi", "Pollachi V. Jayaraman"),
    ("Valparai", "D. Lakshmana Singh"),
    ("Udumalaipettai", "Udumalai K. Radhakrishnan"),
    ("Palani", "K. Ravi Manoharan"),
    ("Attur", "A. Viswanathan"),
    ("Nilakottai", "S. Thenmozhi"),
    ("Vedasandur", "Dr. V.P.B. Paramasivam"),
    ("Aravakurichi", "K. Selvakumar"),
    ("Krishnarayapuram", "Dr. S. Divya"),
    ("Kulithalai", "S. Karunakaran"),
    ("Manapparai", "Dr. P.L. Vijayakumar"),
    ("Srirangam", "R. Manoharan"),
    ("Tiruchirappalli East", "K. Rajasekaran"),
    ("Thiruverumbur", "P. Kumar"),
    ("Lalgudi", "M. Leema Rose"),
    ("Musiri", "N. Yoganathan"),
    ("Thuraiyur", "E. Saroja"),
    ("Perambalur", "Elambai R. Tamilselvan"),
    ("Neyveli", "Sorathur S. Rajendran"),
    ("Panruti", "K. Mohan"),
    ("Cuddalore", "M.C. Sampath"),
    ("Kurinjipadi", "A. Bhuvanendran"),
    ("Bhuvanagiri", "A. Arunmozhithevan"),
    ("Chidambaram", "K.A. Pandiyan"),
    ("Sirkazhi", "M. Sakthi"),
    ("Poompuhar", "S. Pounraj"),
    ("Nagapattinam", "Thanga Kathiravan"),
    ("Thiruthuraipoondi", "U. Baladandayutham"),
    ("Thiruvidaimarudur", "Ilamathi Subramanian"),
    ("Papanasam", "D. Shanmugaprabu"),
    ("Orathanadu", "M. Sekar"),
    ("Pattukkottai", "C.V. Sekar"),
    ("Peravurani", "Govi Ilango"),
    ("Thirumayam", "P.K. Vairamuthu"),
    ("Sivaganga", "P.R. Senthilnathan"),
    ("Melur", "P. Periyapullan Selvam"),
    ("Madurai East", "Mangulam K. Mahendran"),
    ("Sholavandan", "K. Manickam"),
    ("Madurai North", "Dr. P. Saravanan"),
    ("Usilampatti", "I. Mahendran"),
    ("Andipatti", "A. Logirajan"),
    ("Bodinayakanur", "V.T. Narayanasamy"),
    ("Cumbum", "S.T.K. Jakkaiyan"),
    ("Srivilliputhur", "M. Chandraprabha"),
    ("Virudhunagar", "V.G. Ganesan"),
    ("Aruppukkottai", "S. Sethupathi"),
    ("Paramakudi", "S. Muthiah"),
    ("Thiruvadanai", "Keerthika Muniyasamy"),
    ("Mudukulathur", "Malaysia S. Pandi"),
    ("Vilathikulam", "R. Sathya"),
    ("Thoothukudi", "C.T. Chellappandian"),
    ("Srivaikuntam", "S.P. Shanmuganathan"),
    ("Sankarankovil", "Dr. Dileepan Jaishankar"),
    ("Kadayanallur", "C. Krishnamurali"),
    ("Tenkasi", "S. Selvamohandas"),
    ("Alangulam", "K.R.P. Prabhakaran"),
    ("Tirunelveli", "Thachai N. Ganesharaja"),
    ("Ambasamudram", "Isakki Subbaiah"),
    ("Palayamkottai", "S. Syed Sultan Shamsudeen"),
    ("Kanniyakumari", "N. Thalavaisundaram"),
    ("Thousand Lights", "P. Valarmathi"),
    ("Anna Nagar", "S. Gokula Indira"),
    ("Chepauk-Triplicane", "Adhirajaram"),
    ("Tittakudi", "N. Murugumaran"),
    ("Harbour", "Royapuram R. Mano"),
    ("Virugambakkam", "Virugai V.N. Ravi"),
    ("T. Nagar", "B. Sathyanarayanan"),
    ("Velachery", "M.K. Ashok"),
    ("Sholinganallur", "K.P. Kandhan"),
    ("Dr. Radhakrishnan Nagar", "R.S. Rajesh"),
    ("Villivakkam", "S.R. Vijayakumar"),
    ("Tiruchuli", "M.S.R. Rajavarman"),
    ("Alandur", "S. Saravanan"),
    ("Kolathur", "P. Santhanakrishnan"),
    ("Thiru. Vi. Ka. Nagar", "A. Porkodi"),
    ("Egmore", "Abhishek Rangasamy"),
    ("Alangudi", "T. Vimal"),
]

TVK = [
    ("Perambur", "C. Joseph Vijay"),
    ("Tiruchi East", "C. Joseph Vijay"),
    ("T. Nagar", "N. Anand"),
    ("Villivakkam", "Aadhav Arjuna"),
    ("Gobichettipalayam", "K.A. Sengottaiyan"),
    ("Mylapore", "P. Venkataramanan"),
    ("Tiruchengode", "K.G. Arunraaj"),
    ("Thirupparankundram", "C.T.R. Nirmal Kumar"),
    ("Kumarapalayam", "C. Vijayalakshmi"),
    ("Egmore", "A. Rajmohan"),
    ("Lalgudi", "Ku.Pa. Krishnan"),
    ("Tiruppur North", "V. Sathyabama"),
    ("Thousand Lights", "J.C.D. Prabhakar"),
    ("Tittakudi", "A. Rajasekar"),
    ("Saidapet", "M. Arul Prakasam"),
    ("Valparai", "Dr. A. Sridharan"),
    ("R.K. Nagar", "N. Maria Wilson"),
    ("Kolathur", "V.S. Babu"),
    ("Sholavandan", "M.V. Karuppiah"),
    ("Nanguneri", "Reddiapatti Narayanan"),
    ("Gummidipoondi", "S. Vijayakumar"),
    ("Ponneri", "Dr. M.S. Ravi"),
    ("Tiruttani", "M. Sathyakumar"),
    ("Tiruvallur", "Dr. T. Arun Kumar"),
    ("Poonamallee", "R. Prakasam"),
    ("Avadi", "R. Rameshkumar"),
    ("Maduravoyal", "P. Revanth Saran"),
    ("Ambattur", "G. Balamurugan"),
    ("Madhavaram", "M.L. Vijay Prabhu"),
    ("Thiruvottiyur", "N. Senthil Kumar"),
    ("Thiru-Vi-Ka-Nagar", "M.R. Pallavi"),
    ("Royapuram", "K.V. Vijay Thamu"),
    ("Harbour", "Sinora P.S. Ashok"),
    ("Chepauk-Thiruvallikeni", "T. Selvam"),
    ("Anna Nagar", "V.K. Ramkumar"),
    ("Virugambakkam", "R. Sabarinathan"),
    ("Velachery", "R. Kumar"),
    ("Shozhinganallur", "P. Saravanamoorthy"),
    ("Alandur", "M. Harish"),
    ("Sriperumbudur", "K. Thennarasu"),
    ("Pallavaram", "J. Kamatchi"),
    ("Tambaram", "D. Sarathkumar"),
    ("Chengalpattu", "S. Thiyagarajan"),
    ("Thiruporur", "B. Vijayaraj"),
    ("Cheyyur", "K. Mohanraja"),
    ("Madurantakam", "E. Ezhil Catherine"),
    ("Uthiramerur", "J. Munirathinam"),
    ("Kancheepuram", "R.V. Ranjith Kumar"),
    ("Arakkonam", "V. Gandhiraj"),
    ("Sholingar", "Dr. G. Kapil"),
    ("Katpadi", "Dr. M. Sudhakar"),
    ("Ranipet", "I. Thaheera"),
    ("Arcot", "G. Vijay Mohan"),
    ("Vellore", "M.M. Vinoth Kannan"),
    ("Anaikattu", "R. Velmurugan"),
    ("Kilvaithinankuppam", "E. Thendral Kumar"),
    ("Gudiyattam", "K. Sindhu"),
    ("Vaniyambadi", "S. Sayed Burhanudeen"),
    ("Ambur", "P. Imthiyas"),
    ("Jolarpet", "C. Munisamy"),
    ("Tirupattur", "Dr. N. Thiruppathi"),
    ("Uthangarai", "P. Kumaravel"),
    ("Bargur", "E. Muralidharan"),
    ("Krishnagiri", "P. Mukundhan"),
    ("Veppanahalli", "S.R. Sambangi"),
    ("Hosur", "M. Ambarish"),
    ("Thalli", "G. Suresh"),
    ("Palacode", "R. Gopi"),
    ("Pennagaram", "C. Gajendran"),
    ("Dharmapuri", "M. Sivan"),
    ("Pappireddippatti", "S. Thilavathi"),
    ("Harur", "K. Rakesh"),
    ("Chengam", "K. Bharathidhasan"),
    ("Tiruvannamalai", "Arul Arumugam"),
    ("Kilpennathur", "D. Raja"),
    ("Kalasapakkam", "C. Elumalai"),
    ("Polur", "R. Abishek"),
    ("Arani", "V. Venkatesh Kumar"),
    ("Cheyyar", "Dusi K. Mohan"),
    ("Vandavasi", "M. Udhayakumar"),
    ("Gingee", "V. Chandrasekaran"),
    ("Mailam", "A. Vijay Niranjan"),
    ("Tindivanam", "S. Sakthivel"),
    ("Vanur", "G.P. Suresh"),
    ("Villupuram", "N. Mohanraj"),
    ("Vikravandi", "A. Vijay Vadivel"),
    ("Tirukkoyilur", "Vijay R. Baranibalaji"),
    ("Ulundurpettai", "M. Sudhakar"),
    ("Rishivandiyam", "G. Ashok Kumar"),
    ("Sankarapuram", "A. Jagadeesan"),
    ("Kallakurichi", "C. Arul Vignesh"),
    ("Gangavalli", "V. Sujatha"),
    ("Attur", "R. Selvabharathi"),
    ("Yercaud", "J. Lakshmi"),
    ("Omalur", "R.V. Adhiyaman"),
    ("Mettur", "K. Selvam"),
    ("Edappadi", "M. Arunkumar"),
    ("Sangagiri", "Senthilkumar"),
    ("Salem West", "S. Lakshmanan"),
    ("Salem North", "K. Sivakumar"),
    ("Salem South", "A. Vijay Tamilan Parthiban"),
    ("Veerapandi", "M.S. Palanivel"),
    ("Rasipuram", "D. Lokesh Dhanapal"),
    ("Senthamangalam", "P. Chandrasekar"),
    ("Namakkal", "C.S. Dileep"),
    ("Paramathi-Velur", "A. Nandhakumar"),
    ("Erode East", "M. Vijay Balaji"),
    ("Erode West", "K.K. Anand Mohan"),
    ("Modakkurichi", "D. Shanmugam"),
    ("Dharapuram", "S. Gowri Chithra"),
    ("Kangeyam", "P. Mani"),
    ("Perundurai", "V.P. Arunachalam"),
    ("Bhavani", "M.P. Balakrishnan"),
    ("Anthiyur", "M. Vijay Venkatesh"),
    ("Bhavanisagar", "V.P. Tamil Selvi"),
    ("Udhagamandalam", "R. Ibrahim"),
    ("Gudalur", "A. Deepak Sai Kishore"),
    ("Coonoor", "C. Thangaraju"),
    ("Mettuppalayam", "N. Sunil Anand"),
    ("Avanashi", "S. Kamali"),
    ("Tiruppur South", "S. Balamurugan"),
    ("Palladam", "K. Ramkumar"),
    ("Sulur", "N.M. Sukumar"),
    ("Kavundampalayam", "R.D. Kanimozhi"),
    ("Coimbatore North", "V. Sampathkumar"),
    ("Thondamuthur", "R. Sathish Raju"),
    ("Coimbatore South", "V. Senthil Kumar"),
    ("Singanallur", "K.S. Giriprasath"),
    ("Kinathukadavu", "K. Vignesh"),
    ("Pollachi", "G. Ramanathan"),
    ("Udumalaipettai", "G.K. Shankar"),
    ("Madathukulam", "R. Thirumalai"),
    ("Palani", "Dr. M. Praveen Kumar"),
    ("Oddanchatram", "S. Mohan"),
    ("Athoor", "N. Kalaiselvi"),
    ("Nilakkottai", "R. Ayyanar"),
    ("Natham", "L.N. Ramesh"),
    ("Dindigul", "G. Nazeer Raja"),
    ("Vedasandur", "Dr. N. Nagajothi"),
    ("Aravakurichi", "P. Karthikeyan"),
    ("Karur", "V.P. Mathiyazhagan"),
    ("Krishnarayapuram", "S. Madhan"),
    ("Kulithalai", "G. Balasubramani"),
    ("Manapparai", "R. Kathiravan"),
    ("Srirangam", "S. Ramesh"),
    ("Tiruchi West", "G. Ramamoorthy"),
    ("Thiruverumbur", "Navalpattu S. Viji"),
    ("Manachanallur", "V. Saravanan"),
    ("Musiri", "M. Vignesh"),
    ("Thuraiyur", "M. Ravishankar"),
    ("Perambalur", "K. Sivakumar"),
    ("Kunnam", "M. Revathi"),
    ("Ariyalur", "M. Sivakumar"),
    ("Jayankondam", "Kavitha G. Rajendran"),
    ("Vridhachalam", "S. Vijay"),
    ("Neyveli", "K. Anand"),
    ("Panruti", "M. Manikandan"),
    ("Cuddalore", "B. Rajkumar"),
    ("Kurinjipadi", "D. Rajkumar"),
    ("Bhuvanagiri", "T. Mahalingam"),
    ("Chidambaram", "Dr. N. Pari"),
    ("Kattumannarkoil", "Dr. S. Seenuvasan"),
    ("Sirkazhi", "C.S. Gopinath"),
    ("Mayiladuthurai", "S.S. Haroon Rasheeth"),
    ("Poompuhar", "J. Vijayalayan"),
    ("Nagapattinam", "M. Sukumar"),
    ("Kilvelur", "T.A.P. Senthil Pandiyan"),
    ("Vedaranyam", "A. Kingsley Gerald"),
    ("Thiruthuraipoondi", "S. Pandiyan"),
    ("Mannargudi", "U.V.M. Rajarajan"),
    ("Thiruvarur", "V. Veeramani"),
    ("Nannilam", "S. Prabhakaran"),
    ("Thiruvidaimarudur", "S. Prabhakaran"),
    ("Kumbakonam", "R. Vinoth"),
    ("Papanasam", "U. Azarudeen"),
    ("Thiruvaiyaru", "M. Manikandan"),
    ("Thanjavur", "R. Vijay Saravanan"),
    ("Orathanadu", "K. Aravind"),
    ("Pattukkottai", "C. Madhan"),
    ("Peravurani", "D. Chandrakaandeeban"),
    ("Gandharvakottai", "N. Subramanian"),
    ("Viralimalai", "P. Murugesan"),
    ("Pudukkottai", "K.M. Shareef"),
    ("Thirumayam", "C. Sindhamani"),
    ("Alangudi", "Durai Kandasamy"),
    ("Aranthangi", "J. Mohamad Parvez"),
    ("Karaikudi", "Dr. T.K. Prabhu"),
    ("Tiruppattur", "Srinivasa Sethupathi"),
    ("Sivaganga", "Kulandhai Rani Nachiar"),
    ("Manamadurai", "D. Ilangovan"),
    ("Melur", "A. Madurai Veeran"),
    ("Madurai East", "S. Karthikeyan"),
    ("Madurai North", "A. Kallanai"),
    ("Madurai South", "J. Jo Peter"),
    ("Madurai Central", "V.M.S. Mustafa"),
    ("Madurai West", "S.R. Thangapandi"),
    ("Thirumangalam", "N. Sathishkumar"),
    ("Usilampatti", "M. Vijay"),
    ("Andipatti", "V. Pandi"),
    ("Periyakulam", "G. Sabari"),
    ("Bodinayakanur", "S. Prakash"),
    ("Cumbum", "P.L.A. Jaganath Mishra"),
    ("Rajapalayam", "K. Jagadeeswari"),
    ("Srivilliputhur", "A. Karthik"),
    ("Sattur", "M. Ajith"),
    ("Sivakasi", "S. Keerthana"),
    ("Virudhunagar", "S.P. Selvam"),
    ("Aruppukkottai", "K. Karthik Kumar"),
    ("Tiruchuli", "S. Samayan"),
    ("Paramakudi", "G. Gopirajan"),
    ("Tiruvadanai", "V.K. Rajiv"),
    ("Ramanathapuram", "E.A. Sahul Hameed"),
    ("Mudukulathur", "B. Malarvizhi Jayabala"),
    ("Vilathikulam", "P. Kasiram"),
    ("Thoothukudi", "A. Srinath"),
    ("Tiruchendur", "J. Murugan"),
    ("Srivaikuntam", "G. Saravanan"),
    ("Ottapidaram", "P. Madhanraja"),
    ("Kovilpatti", "S. Balasubramanian"),
    ("Sankarankovil", "C. Ramarajan"),
    ("Vasudevanallur", "R. Amudha Rani"),
    ("Kadayanallur", "R.K. Abdul Jalil"),
    ("Tenkasi", "A. Rajaprakash"),
    ("Alangulam", "V. Vipin Chakravarthi"),
    ("Tirunelveli", "R.S. Murugan"),
    ("Ambasamudram", "S. Rajagopal"),
    ("Palayamkottai", "S. Maria John"),
    ("Radhapuram", "K. Satheesh Christopher"),
    ("Kanniyakumari", "S.R. Madhavan"),
    ("Nagercoil", "G. Perveen King"),
    ("Colachel", "Dr. Prem Alex Lawrence"),
    ("Padmanabhapuram", "S. Krishnakumar"),
    ("Vilavancode", "K. Michael Kumar"),
    ("Killiyoor", "S. Sabeen"),
]

CPIM = [
    ("Gandharvakottai", "M. Chinnadurai"),
    ("Kilvelur", "D. Latha"),
    ("Padmanabhapuram", "R. Chellasamy"),
    ("Palani", "N. Pandi"),
    ("Thiruvottiyur", "L. Sundararajan"),
]

PMK = [
    ("Perambur", "M. Thilagabama"),
    ("Dharmapuri", "Dr. Sowmiya Anbumani"),
    ("Vridhachalam", "Dr. Tamilarasi Adhimoolam"),
    ("Salem West", "M. Karthi"),
    ("Pennagaram", "Paadi V. Selvam"),
    ("Polur", "C.R. Bhaskaran"),
    ("Thiruporur", "K. Balu"),
    ("Jayankondam", "K. Vaithi"),
    ("Salem North", "S. Sadasivam"),
    ("Vikravandi", "C. Sivakumar"),
    ("Sholingur", "K. Saravanan"),
    ("Mayiladuthurai", "Sithamalli A. Palanichamy"),
    ("Uthiramerur", "P. Maheshkumar"),
    ("Rishivandiyam", "A.P. Chezhiyan"),
    ("Kattumannarkoil", "Dr. Anbu Cholan"),
]

VCK = [
    ("Tindivanam", "Vanniyarasu"),
    ("Periyakulam", "Sakthivel"),
    ("Kallakurichi", "Malathi"),
    ("Panruti", "Abdul Rahman"),
    ("Kattumannarkoil", "Thol. Thirumavalavan"),
    ("Cheyyur", "Sindhanai Selvan"),
    ("Arakkonam", "Ezhil Caroline"),
    ("Thiruporur", "Panneerdas"),
]

CPI = [
    ("Bhavanisagar", "P.L. Sundaram"),
    ("Thalli", "T. Ramachandran"),
    ("Srivilliputhur", "P. Mahalingam"),
    ("Thiruthuraipoondi", "Marimuthu K."),
    ("Tiruppur (North)", "M. Ravi"),
]

NTK = [
    ("Gummidipoondi", "Sridhar"),
    ("Ponneri", "Rajathi"),
    ("Tiruttani", "Chandran"),
    ("Thiruvallur", "Senthil Kumar"),
    ("Poonamallee", "Mehala"),
    ("Avadi", "Punitha"),
    ("Maduravoyal", "Revathi"),
    ("Ambattur", "Aadhithan"),
    ("Madhavaram", "Kruthika Elumalai"),
    ("Thiruvottiyur", "Sathya Baskar"),
    ("Dr.Radhakrishnan Nagar", "Vennila Thayumanavan"),
    ("Perambur", "Vetrithamizhan"),
    ("Kolathur", "Soundrapandian"),
    ("Villivakkam", "Roshini"),
    ("Thiru-Vi-Ka-Nagar", "Jegadeesh Chander"),
    ("Egmore", "Saranya"),
    ("Royapuram", "Babumailan"),
    ("Harbour", "Rufhkhan Sheriff"),
    ("Chepauk-Thiruvallikeni", "Ayisha Beham"),
    ("Thousand Lights", "Kalanjiyam"),
    ("Anna Nagar", "C. Shankar"),
    ("Virugambakkam", "Santhosh"),
    ("Saidapet", "Srividhya"),
    ("T. Nagar", "Anusha Vijayakumar"),
    ("Mylapore", "Arun"),
    ("Velachery", "Keerthana"),
    ("Sholinganallur", "jayalakshmi Raman"),
    ("Alandur", "Mahalakshmi"),
    ("Sriperumbudur", "Sindhu"),
    ("Pallavaram", "Karthikeyan"),
    ("Tambaram", "Tamilselvi"),
    ("Chengalpattu", "Amutha Nambiyar"),
    ("Thiruporur", "Ambethrajan"),
    ("Cheyyur", "Swathi Lakshmi"),
    ("Madurantakam", "Janaki Raman"),
    ("Uthiramerur", "Maram maasilamani"),
    ("Kancheepuram", "Vetriselvi"),
    ("Arakkonam", "Raj Kumar"),
    ("Sholingur", "Ashok Kumar"),
    ("Katpadi", "Thirukumaran"),
    ("Ranipet", "Tharikka salman"),
    ("Arcot", "Archaha"),
    ("Vellore", "Soniya"),
    ("Anaikattu", "Ravi Kumar"),
    ("Kilvaithinankuppam", "Kalaiyendri"),
    ("Gudiyattam", "Imalan"),
    ("Vaniyambadi", "Murugesan"),
    ("Ambur", "Afsia Thoufic Bikrid"),
    ("Jolarpet", "Sasi Rekha"),
    ("Tirupattur", "Aarumugam"),
    ("Uthangarai", "Megala"),
    ("Bargur", "Kavin"),
    ("Krishnagiri", "Suganthi Parthiban"),
    ("Veppanahalli", "Nagaraj"),
    ("Hosur", "Stalin"),
    ("Thalli", "Narasimman"),
    ("Palacode", "Boopathy"),
    ("Pennagaram", "Palaniyammal"),
    ("Dharmapuri", "Santha Lakshmi"),
    ("Pappireddippatti", "Archana Tamil Aruvi"),
    ("Harur", "Anitha Annadurai"),
    ("Chengam", "J Shobha"),
    ("Tiruvannamalai", "Vignesh"),
    ("Kilpennathur", "V. Loganathan"),
    ("Kalasapakkam", "Seetha"),
    ("Polur", "umadevi prakash"),
    ("Arani", "Thavamani Ramesh"),
    ("Cheyyar", "Tamil Selvan"),
    ("Vandavasi", "Ganesh"),
    ("Gingee", "Krishnan"),
    ("Mailam", "Vijay Vikram"),
    ("Tindivanam", "Petchimuthu"),
    ("Vanur", "Karikazhan"),
    ("Villupuram", "Abhinaya Ponnivalavan"),
    ("Vikravandi", "Suba chandrasekaran"),
    ("Tirukkoyilur", "Hemarajan"),
    ("Ulundurpettai", "Logeshwari"),
    ("Rishivandiyam", "Radhika"),
    ("Sankarapuram", "Ramesh"),
    ("Kallakurichi", "Nagammal"),
    ("Gangavalli", "Abirami Neduncheralathan"),
    ("Attur", "Monisha chinnadurai"),
    ("Yercaud", "Palanisamy"),
    ("Omalur", "Siva Sakthi"),
    ("Mettur", "Vidhya Veerapan"),
    ("Edappadi", "Priyadharshini"),
    ("Sankari", "Nithya Arul"),
    ("Salem (West)", "Suresh Kumar"),
    ("Salem (North)", "Gunaseela"),
    ("Salem (South)", "Sophiya"),
    ("Veerapandi", "Rajesh Kumar"),
    ("Rasipuram", "Sasikala"),
    ("Senthamangalam", "Ponnumani"),
    ("Namakkal", "Praveen"),
    ("Paramathi-Velur", "Aravindh"),
    ("Tiruchengode", "Revathi"),
    ("Kumarapalayam", "Yuvarani"),
    ("Erode (East)", "Thandava Moorthy"),
    ("Erode (West)", "Vijay"),
    ("Modakkurichi", "Arun"),
    ("Dharapuram", "divya"),
    ("Kangayam", "Karmegan"),
    ("Perundurai", "Logu"),
    ("Bhavani", "Menaka Devi"),
    ("Anthiyur", "Anandhi"),
    ("Gobichettipalayam", "Seetha Lakshmi"),
    ("Bhavanisagar", "Soundarya"),
    ("Udhagamandalam", "Ragupathu Deepan"),
    ("Gudalur", "Karthik Ramakrishnan"),
    ("Coonoor", "dheenu"),
    ("Mettupalayam", "Gopalakrishnan"),
    ("Avanashi", "Menaga"),
    ("Tiruppur (North)", "Abhinaya"),
    ("Tiruppur (South)", "Perarivalan"),
    ("Palladam", "Thamizhinian"),
    ("Sulur", "Rajasekhar"),
    ("Kavundampalayam", "Kalamani"),
    ("Coimbatore (North)", "Narmatha"),
    ("Thondamuthur", "Rajabunisha"),
    ("Coimbatore (South)", "Perarivalan"),
    ("Singanallur", "Nehruji"),
    ("Kinathukadavu", "Banupriya senthil kumar"),
    ("Pollachi", "Senthil"),
    ("Valparai", "Uma Devi"),
    ("Udumalaipettai", "Ram Kumar"),
    ("Madathukulam", "Radhamani"),
    ("Palani", "Murugeshwari"),
    ("Oddanchatram", "Ragupathi"),
    ("Athoor", "Simon Justin"),
    ("Nilakkottai", "Kailai Rajan"),
    ("Natham", "Alagammal"),
    ("Dindigul", "Mutharasi"),
    ("Vedasandur", "Hussain"),
    ("Aravakurichi", "Narain"),
    ("Karur", "Karuppaiah"),
    ("Krishnarayapuram", "Sathya"),
    ("Kulithalai", "Nanmaran"),
    ("Manapparai", "Arunagiri"),
    ("Srirangam", "Dharmaraj"),
    ("Tiruchirappalli (West)", "Bhuvaneshwari"),
    ("Tiruchirappalli (East)", "Krishnasamy"),
    ("Thiruverumbur", "Jallikattu Rajesh"),
    ("Lalgudi", "Madhan"),
    ("Manachanallur", "Thenmozhi"),
    ("Musiri", "Bakya Lakshmi"),
    ("Thuraiyur", "Gowsalya Suresh"),
    ("Perambalur", "Johnsy Rani"),
    ("Kunnam", "Keerthi vasan"),
    ("Ariyalur", "Pugalendhi"),
    ("Jayankondam", "Revathi Kalaimani"),
    ("Tittakudi", "Mahalakshmi"),
    ("Vridhachalam", "Amudha nambi"),
    ("Neyveli", "Veeramani"),
    ("Panruti", "Banu Priya"),
    ("Cuddalore", "sarasu"),
    ("Kurinjipadi", "Sengolan"),
    ("Bhuvanagiri", "Sumathi Srinivasan"),
    ("Chidambaram", "Tamil"),
    ("Kattumannarkoil", "Sivajothi"),
    ("Sirkazhi", "Subash"),
    ("Mayiladuthurai", "Kasiraman"),
    ("Poompuhar", "Ilaiya Nagulan"),
    ("Nagapattinam", "Fathima Farhana"),
    ("Kilvelur", "Karthiga"),
    ("Vedaranyam", "Idumbavanam Karthik"),
    ("Thiruthuraipoondi", "Vinothini"),
    ("Mannargudi", "Bharathi Selvan"),
    ("Thiruvarur", "Ashwini"),
    ("Nannilam", "Theanmozhi Dileep Kumar"),
    ("Thiruvidaimarudur", "Divya Bharathi"),
    ("Kumbakonam", "Ananth"),
    ("Papanasam", "Aneesh Fathima"),
    ("Thiruvaiyaru", "Senthilnathan"),
    ("Thanjavur", "Krishna Kumar"),
    ("Orathanadu", "Thirumurugan"),
    ("Pattukkottai", "Kannan"),
    ("Peravurani", "Rajaram"),
    ("Gandharvakottai", "Nadiya Tamilselvan"),
    ("Viralimalai", "Sathya Laxshmi"),
    ("Pudukkottai", "Ezhilarasi"),
    ("Thirumayam", "Lakshmi Srinivasan"),
    ("Alangudi", "Rajaraman"),
    ("Aranthangi", "Muthu Lakshmi"),
    ("Karaikudi", "Seeman"),
    ("Tiruppattur", "Ramya mohan"),
    ("Sivaganga", "Indhuja Ramesh"),
    ("Manamadurai", "Shanmugapriya"),
    ("Melur", "Kottai Kumar"),
    ("Madurai East", "Selvam"),
    ("Sholavandan", "Nagalakshmi Thirumaran"),
    ("Madurai North", "Thirunavukkarasu"),
    ("Madurai South", "Sathya devi"),
    ("Madurai Central", "Durga kumaraswamy"),
    ("Madurai West", "Vignesh kumar"),
    ("Thirupparankundram", "Sathya devi"),
    ("Thirumangalam", "Munis"),
    ("Usilampatti", "Abirami Dhanapal"),
    ("Andipatti", "Arunadevi"),
    ("Periyakulam", "Vimala"),
    ("Bodinayakanur", "Kalaiyarasu"),
    ("Cumbum", "Anbu Selvi"),
    ("Rajapalayam", "Karthik"),
    ("Srivilliputhur", "Karikala pandiyan"),
    ("Sattur", "Anandha Raja"),
    ("Sivakasi", "Dayana"),
    ("Virudhunagar", "Laxmanan"),
    ("Aruppukkottai", "Manimaran"),
    ("Tiruchuli", "Karthick raja"),
    ("Paramakudi", "Ezhil izhavarasi"),
    ("Tiruvadanai", "Premnath"),
    ("Ramanathapuram", "Muthu kesavan"),
    ("Mudukulathur", "Chandra Prabha"),
    ("Vilathikulam", "Balaji"),
    ("Thoothukudi", "Jacob Abhishek devadasan"),
    ("Tiruchendur", "Obiliya"),
    ("Srivaikuntam", "Shanmugasundaram"),
    ("Ottapidaram", "Anusiya"),
    ("Kovilpatti", "Pandi"),
    ("Sankarankovil", "Kavitha"),
    ("Vasudevanallur", "Isai Mathivanan"),
    ("Kadayanallur", "Abubakar Siddique"),
    ("Tenkasi", "Gowshik Pandiyan"),
    ("Alangulam", "Palraj"),
    ("Tirunelveli", "Sathya"),
    ("Ambasamudram", "Sivasankaran"),
    ("Palayamkottai", "Sankara narayanan"),
    ("Nanguneri", "Selvam"),
    ("Radhapuram", "Girija Thamaraipandiyan"),
    ("Kanniyakumari", "Maria Jenifer"),
    ("Nagercoil", "Muthukumar"),
    ("Colachel", "Ancy Sobha Rani"),
    ("Padmanabhapuram", "Seelan"),
    ("Vilavancode", "Maria Stella"),
    ("Killiyoor", "Himler"),
]


# ---------------------------------------------------------------------------
# Clean + write
# ---------------------------------------------------------------------------


def clean_name(name: str) -> str:
    """Remove honorifics and clean candidate name."""
    name = name.strip()
    for prefix in ("Shri ", "Smt. ", "Smt ", "Prof. ", "Adv. ", "Ms. ", "Mrs. ", "Mr. "):
        if name.startswith(prefix):
            name = name[len(prefix):]
    return name.strip()


def clean_constituency(name: str) -> str:
    """Normalize constituency name to uppercase, strip SC/ST suffixes for matching."""
    name = name.strip()
    # Remove (SC), (ST), - SC, - ST suffixes for cleaner matching
    name = re.sub(r"\s*[-–]\s*(SC|ST)\s*$", "", name, flags=re.IGNORECASE)
    name = re.sub(r"\s*\((SC|ST)\)\s*$", "", name, flags=re.IGNORECASE)
    return name.upper().strip()


def main():
    all_rows = []
    for party, candidates in [
        ("DMK", DMK),
        ("AIADMK", AIADMK),
        ("TVK", TVK),
        ("INC", INC),
        ("BJP", BJP),
        ("CPIM", CPIM),
        ("CPI", CPI),
        ("PMK", PMK),
        ("VCK", VCK),
        ("NTK", NTK),
    ]:
        for constituency, candidate in candidates:
            all_rows.append({
                "party": party,
                "constituency": clean_constituency(constituency),
                "candidate": clean_name(candidate),
            })

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=["party", "constituency", "candidate"])
        writer.writeheader()
        writer.writerows(all_rows)

    print(f"Wrote {len(all_rows)} candidates to {OUT}")
    from collections import Counter
    parties = Counter(r["party"] for r in all_rows)
    for party, count in parties.most_common():
        print(f"  {party}: {count}")


if __name__ == "__main__":
    main()
