# Generated by Django 4.2.27 on 2026-01-26 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ta', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('contesting', 'Contesting')], default='applied', max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('education_ta', models.CharField(blank=True, max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255)),
                ('profession_ta', models.CharField(blank=True, max_length=255)),
                ('address', models.TextField(blank=True)),
                ('address_ta', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_ta', models.CharField(blank=True, max_length=255)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('district_ta', models.CharField(blank=True, max_length=255)),
                ('reservation_category', models.CharField(blank=True, max_length=50)),
                ('reservation_category_ta', models.CharField(blank=True, max_length=50)),
                ('boundary_geojson', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_ta', models.CharField(blank=True, max_length=255)),
                ('abbreviation', models.CharField(blank=True, max_length=50)),
                ('abbreviation_ta', models.CharField(blank=True, max_length=50)),
                ('symbol_url', models.URLField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('source_type', models.CharField(choices=[('official', 'Official'), ('adr', 'ADR/MyNeta'), ('media', 'Media')], max_length=20)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcedocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Manifesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('summary_ta', models.TextField(blank=True)),
                ('document_url', models.URLField(blank=True, max_length=1000)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos', to='core.candidate')),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos', to='core.constituency')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos', to='core.party')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcedocument')),
            ],
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=255)),
                ('court', models.CharField(blank=True, max_length=255)),
                ('court_ta', models.CharField(blank=True, max_length=255)),
                ('sections', models.CharField(blank=True, max_length=255)),
                ('sections_ta', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('status_ta', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ta', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to='core.candidate')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcedocument')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='constituency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.constituency'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.party'),
        ),
        migrations.CreateModel(
            name='Affidavit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criminal_cases_count', models.PositiveIntegerField(blank=True, null=True)),
                ('serious_criminal_cases_count', models.PositiveIntegerField(blank=True, null=True)),
                ('assets_total', models.BigIntegerField(blank=True, null=True)),
                ('liabilities_total', models.BigIntegerField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('education_ta', models.CharField(blank=True, max_length=255)),
                ('additional_details', models.JSONField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affidavits', to='core.candidate')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcedocument')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('name', 'constituency')},
        ),
    ]
