# Generated by Django 4.2.27 on 2026-01-26 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_candidate_status_election_candidateresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateresult",
            name="vote_share",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
