# Generated by Django 4.2.27 on 2026-02-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_candidateresult_vote_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coalition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_ta', models.CharField(blank=True, max_length=255)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coalitions', to='core.election')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ManifestoPromise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255)),
                ('text', models.TextField(blank=True)),
                ('text_ta', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('is_key', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manifesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises', to='core.manifesto')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromiseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('state', 'State'), ('constituency', 'Constituency')], max_length=20)),
                ('status', models.CharField(choices=[('fulfilled', 'Fulfilled'), ('partial', 'Partially fulfilled'), ('not_fulfilled', 'Not fulfilled'), ('unknown', 'Unknown/Unverified'), ('disputed', 'Disputed')], default='unknown', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('summary', models.TextField(blank=True)),
                ('summary_ta', models.TextField(blank=True)),
                ('as_of', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('constituency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.constituency')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.party')),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='core.manifestopromise')),
            ],
            options={
                'ordering': ['-as_of', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromiseEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('quote', models.TextField(blank=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='core.promiseassessment')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcedocument')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyFulfilmentClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=255)),
                ('as_of', models.DateField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.election')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulfilment_claims', to='core.party')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcedocument')),
            ],
            options={
                'ordering': ['-as_of', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ManifestoDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ta', 'Tamil')], max_length=2)),
                ('url', models.URLField(max_length=1000)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('manifesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.manifesto')),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sourcedocument')),
            ],
            options={
                'ordering': ['manifesto_id', 'language'],
            },
        ),
        migrations.CreateModel(
            name='CoalitionMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coalition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.coalition')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coalition_memberships', to='core.party')),
            ],
            options={
                'ordering': ['coalition__name', 'party__name'],
            },
        ),
        migrations.AddField(
            model_name='manifesto',
            name='coalition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manifestos', to='core.coalition'),
        ),
        migrations.AddConstraint(
            model_name='promiseassessment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('scope', 'state'), ('party__isnull', False), ('constituency__isnull', True)), models.Q(('scope', 'constituency'), ('constituency__isnull', False)), ('scope__isnull', True), _connector='OR'), name='promise_assessment_scope_party_or_constituency'),
        ),
        migrations.AddConstraint(
            model_name='promiseassessment',
            constraint=models.CheckConstraint(check=models.Q(('score__isnull', True), models.Q(('score__gte', 0), ('score__lte', 1)), _connector='OR'), name='promise_assessment_score_between_0_and_1'),
        ),
        migrations.AddIndex(
            model_name='manifestopromise',
            index=models.Index(fields=['manifesto', 'is_key'], name='core_manife_manifes_c503c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manifestopromise',
            unique_together={('manifesto', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='manifestodocument',
            unique_together={('manifesto', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='coalitionmembership',
            unique_together={('coalition', 'party')},
        ),
    ]
