# Generated by Django 4.2.28 on 2026-02-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coalition_manifestopromise_promiseassessment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ease_of_use', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('helps_inform', models.CharField(blank=True, max_length=20)),
                ('would_return', models.CharField(blank=True, max_length=20)),
                ('suggestion', models.TextField(blank=True)),
                ('page_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
