# Generated by Django 4.2.27 on 2026-02-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='agricultural_workers_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='anaemia_women_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='area_sq_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='banking_access_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='bpl_households_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='child_stunting_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='child_wasting_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='crime_rate_per_lakh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='crimes_against_sc_st_per_lakh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='crimes_against_women_per_lakh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='electricity_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='female_literacy_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='full_immunization_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='graduate_and_above_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='infant_mortality_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='institutional_delivery_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='literacy_gender_gap_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='literacy_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='male_literacy_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='parliamentary_constituency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='constituency',
            name='per_capita_income_inr',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='pucca_housing_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='constituency',
            name='sanitation_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='secondary_education_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='tap_water_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='under5_mortality_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='unemployment_rate_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='constituency',
            name='urbanization_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='party',
            name='current_leader',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='eci_recognition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='party',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='founder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='governance_record_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='party',
            name='headquarters',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='party',
            name='political_ideology',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='party',
            name='political_position',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
